Arranged files.

diff --git a/broadcast b/broadcast
--- a/broadcast
+++ b/broadcast
@@ -28,16 +28,16 @@ if [ "${OUTPUT_URI}x" = "x" ]; then
               swfUrl=${RTMP_URI}"
 fi
 
-if [ -e ${SOURCEDIR}/config ]; then  
-  . ${SOURCEDIR}/config || exit 1
+if [ -e ${SOURCEDIR}/config/global ]; then  
+  . ${SOURCEDIR}/config/global || exit 1
 else
-  echo "Can't open config file." >2
+  echo "Can't open config/global file." >2
   exit 1
 fi
-if [ -e ${SOURCEDIR}/broadcast.d/${BROADCASTER} ]; then
-  . ${SOURCEDIR}/broadcast.d/${BROADCASTER}
+if [ -e ${SOURCEDIR}/config/broadcast.d/${BROADCASTER} ]; then
+  . ${SOURCEDIR}/config/broadcast.d/${BROADCASTER}
 else
-  echo "Can't open broadcast.d/${BROADCASTER}" >2
+  echo "Can't open config/broadcast.d/${BROADCASTER}" >2
   exit 2
 fi
 
diff --git a/record b/record
--- a/record
+++ b/record
@@ -8,9 +8,13 @@
 SOURCEDIR=$(dirname "$0")
 OUTPUT_FILE="${1:-record.dat}"
 
-. ${SOURCEDIR}/config
+if [ -e ${SOURCEDIR}/config/global ]; then
+  . ${SOURCEDIR}/config
+else
+  echo "Can't open config/global file." >2
+  exit 1
+fi
 
-# --- Muxing video/audio and saving to a file with ffmpeg.
 ffmpeg -y -threads 0 \
        -f ${VIDEO_SRC_FMT} -i ${VIDEO_SRC_DEV} \
        -f ${AUDIO_SRC_FMT} -i ${AUDIO_SRC_DEV} \
@@ -18,6 +22,5 @@ ffmpeg -y -threads 0 \
        -acodec libvorbis -aq 6 \
        -f matroska \
        "${OUTPUT_FILE}" &
-
 wait
 
